[build]
  # Build command - only build the frontend for Netlify
  command = "vite build"
  
  # Publish directory - where the built frontend files are located
  publish = "dist/public"

[build.environment]
  # Node.js version for build
  NODE_VERSION = "18"

# SPA redirect rules (backup to _redirects file)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Static file caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"