[build]
  # Build command - run vite build from repo root to use correct config
  command = "vite build"
  
  # Publish directory - where the built frontend files are located (from vite.config.ts outDir)
  publish = "dist/public"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version for build
  NODE_VERSION = "18"

# API routes redirect to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# SPA redirect rules for frontend routing (lower priority)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Static file caching
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"